# Use the latest PowerShell Core image
FROM mcr.microsoft.com/powershell:latest

# Create a working directory
WORKDIR /app

# Copy the contents of src into /app/
COPY src/ /app/

# Run the setup script
# RUN pwsh /app/setup_for_script.ps1
